[package]
name = "rmnist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfdx = { version = "0.11.2", features = [ "safetensors"] }
indicatif = "0.17.3"
mnist = "0.5.0"
rand = "0.8.5"
